export enum CONTROLLER_ENUM {
    TOP = "TOP",
    BOTTOM = "BOTTOM",
    LEFT = "LEFT",
    RIGHT = "RIGHT",
    TURNLEFT = "TURNLEFT",
    TURNRIGHT = "TURNRIGHT",
}

export enum DIRECTION_ENUM {
    TOP = "TOP",
    BOTTOM = "BOTTOM",
    LEFT = "LEFT",
    RIGHT = "RIGHT",
}

export enum ENTITY_STATE_ENUM {
    IDLE = "IDLE",
    ATTACK = "ATTACK",
    TURNLEFT = "TURNLEFT",
    TURNRIGHT = "TURNRIGHT",
    BLOCKFRONT = "BLOCKFRONT",
    BLOCKLEFT = "BLOCKLEFT",
    BLOCKRIGHT = "BLOCKRIGHT",
    BLOCKBACK = "BLOCKBACK",
    BLOCKTURNLEFT = "BLOCKTURNLEFT",
    BLOCKTURNRIGHT = "BLOCKTURNRIGHT",
    DEATH = "DEATH",
    AIRDEATH = "AIRDEATH",
}

export enum DIRECTION_ORDER_ENUM {
    TOP = 0,
    BOTTOM = 1,
    LEFT = 2,
    RIGHT = 3,
}

export enum ENTITY_TYPE_ENUM {
    PLAYER = "PLAYER",
}
