export enum EVENT_ENUM {
    NEXT_LEVEL = "NEXT_LEVEL",
    PLAYER_CTRL = "PLAYER_CTRL",
    PLAYER_MOVE_END = "PLAYER_MOVE_END",
    PLAYER_BORN = "PLAYER_BORN",
    ATTACK_PLAYER = "ATTACK_PLAYER",
    ATTACK_ENEMY = "ATTACK_ENEMY",
    DOOR_OPEN = "DOOR_OPEN",
}
