export enum FSM_PARAMS_TYPE_ENUM {
    NUMBER = "NUMBER",
    TRIGGER = "TRIGGER",
}

export enum PARAMS_NAME_ENUM {
    IDLE = "IDLE",
    TURNLEFT = "TURNLEFT",
    TURNRIGHT = "TURNRIGHT",
    BLOCKFRONT = "BLOCKFRONT",
    BLOCKLEFT = "BLOCKLEFT",
    BLOCKRIGHT = "BLOCKRIGHT",
    BLOCKBACK = "BLOCKBACK",
    BLOCKTURNLEFT = "BLOCKTURNLEFT",
    BLOCKTURNRIGHT = "BLOCKTURNRIGHT",
    DIRECTION = "DIRECTION",
}
